### ISSUE TITLE
Application development

### ISSUE THREAD

**Issue by anyulled** [ConfluxHQ/software-delivery-assessment#18]
Hi! is it okay if I develop a web application based on the questions in this assessment and publish it under the same license as you have here?

I really think this assessment is very valuable and would like to have a tool to keep track of how the teams are historically measuring it.

Ideally, I'll include also infrastructure as code to be able to deploy in the three main cloud providers.

**Comment by matthewskelton** [comment]
HI @anyulled - this sounds great! Looking forward to seeing the website :) Obviously, as you say, the website needs to be CC BY-SA.

Thank you :)

**Comment by matthewskelton** [comment]
Hi @ersiner what's the implication of the repo being MIT licensed?

**Comment by ersiner** [comment]
That's what I am asking. Is this intended? I don't know whether this is a conflict to be resolved. I did not come across such a situation before (or I did not pay attention).

**Comment by matthewskelton** [comment]
Hi @anyulled I switched the repo to use CC BY-SA https://github.com/ConfluxHQ/software-delivery-assessment/blob/main/LICENCE.md - how is the web app?

**Comment by anyulled** [comment]
> 

Hi, @matthewskelton thanks for the update. I now have a working version with hard-coded data, and I'm planning to implement user authentication and moving the data structure to a database. I believe I'll have something to show in October.

**Comment by matthewskelton** [comment]
Awesome, @anyulled - I will close this issue for now, as you are not block on this. Looking forward to seeing the product!!
